# Generated by Django 3.2 on 2021-04-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возвраст')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возвраст')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tagline', models.CharField(max_length=255, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('world_premiere', models.DateTimeField(verbose_name='Дата премьеры')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('fees_in_usa', models.IntegerField(verbose_name='Сборы в США')),
                ('fees_in_world', models.IntegerField(verbose_name='Сборы в мире')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('actors', models.ManyToManyField(to='cinema.Actors', verbose_name='Актеры')),
                ('category', models.ManyToManyField(to='cinema.Category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(to='cinema.Directors', verbose_name='Режиссер')),
                ('genre', models.ManyToManyField(to='cinema.Genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.ratingstar')),
            ],
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
    ]
