# Generated by Django 3.2 on 2021-04-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='url',
        ),
        migrations.RemoveField(
            model_name='directors',
            name='url',
        ),
    ]
